rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ruby-head
  - ree
  - rbx-18mode
  - rbx-19mode
  - jruby-18mode
  - jruby-19mode
  - jruby-head

branches:
  only:
    - master

before_install:
  - gem install sinatra
  - gem install random-word
